#!/usr/bin/env bash
# This script is invincible! It catches SIGTERM and displays a message.

# Define what to do when SIGTERM (signal 15) is received
trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
