#!/usr/bin/env bash
# This script displays "Best School" 10 times, but says "Hi" on the 9th iteration
n=1
while [ $n -le 10 ]
do
    echo "Best School"
    if [ $n -eq 9 ]
    then
        echo "Hi"
    fi
    n=$((n + 1))
done
