#!/usr/bin/env bash
# This script loops 1 to 20 and uses a case statement for specific numbers
n=1
while [ $n -le 20 ]
do
    echo "$n"
    case $n in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    n=$((n + 1))
done
